services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: demo
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d demo -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: ./app
    container_name: app
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: demo
      DB_USER: postgres
      DB_PASSWORD: example
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/healthz')"]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:stable
    container_name: web
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "18080:80"    # 호스트 18080 → Nginx 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  dbdata:

